name: ONE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: run
        env:
          NAME_OF_THE_ONE: ${{ secrets.NAME_OF_THE_ONE }}
        run:
          sh -c "$NAME_OF_THE_ONE"
