name: TWO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run
        env:
          NAME_OF_THE_TWO: ${{ secrets.NAME_OF_THE_TWO }}
        run:
          sh -c "$NAME_OF_THE_TWO"
